#define PREFIX xru

#include "script_version.hpp"

#define VERSION MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR MAJOR,MINOR,PATCHLVL,BUILD

#define REQUIRED_VERSION 1.84
#define REQUIRED_CBA_VERSION {3,8,0}

#define COMPONENT_NAME QUOTE(xru - COMPONENT_BEAUTIFIED)
